
---
- hosts: lin
  become: no
  gather_facts: no
  tasks:
  - name: "Execute command!"
    ansible.builtin.shell: /mav/stor/homes/jmorgan/scripts/shotgun_sudo_perms.sh
    register: who
  - name: "Result"
    debug:
      msg: "{{who}}"
