---
- hosts: lin
  become: no
  gather_facts: no
  tasks:
  - name: "Execute command!"
    command: /mav/stor/homes/jmorgan/scripts/whoami.sh
    register: who
  - name: "Result"
    debug:
      msg: "{{who}}"
